import React from 'react';
import '../app/globals.css'; // Updated import path for globals.css
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
  return (
    <>
      {/* Add the metadata here (e.g., title and description) */}
      <html lang="en">
        <head>
          <title>{metadata.title}</title>
          <meta name="description" content={metadata.description} />
          {/* Add any other meta tags or stylesheets your layout might need */}
        </head>
        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
};

export default RootLayout;
